apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-rtmp-recordings-pvc
  namespace: camera-streaming
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-rtmp-hls-pvc
  namespace: camera-streaming
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-rtmp
  namespace: camera-streaming
  labels:
    app: nginx-rtmp
    component: streaming
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-rtmp
  template:
    metadata:
      labels:
        app: nginx-rtmp
        component: streaming
    spec:
      containers:
      - name: nginx-rtmp
        image: tiangolo/nginx-rtmp:latest
        ports:
        - containerPort: 1935
          name: rtmp
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: recordings-storage
          mountPath: /recordings
        - name: hls-storage
          mountPath: /tmp/hls
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-rtmp-config
      - name: recordings-storage
        persistentVolumeClaim:
          claimName: nginx-rtmp-recordings-pvc
      - name: hls-storage
        persistentVolumeClaim:
          claimName: nginx-rtmp-hls-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-rtmp-service
  namespace: camera-streaming
  labels:
    app: nginx-rtmp
    component: streaming
spec:
  selector:
    app: nginx-rtmp
  ports:
  - port: 1935
    targetPort: 1935
    protocol: TCP
    name: rtmp
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-rtmp-hpa
  namespace: camera-streaming
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-rtmp
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60